language: node_js
node_js:
  - "node"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools

script:
  - npm --prefix src install
  - npm --prefix functions install

after_success:
  - firebase deploy --token $FIREBASE-KEY

notifications:
  email:
    on_failure: change
    on_success: change