version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Install nuxt
          command: npm --prefix src install
      - save_cache:
          key: dependency-cache-{{ checksum "src/package-lock.json" }}
          paths:
            - src/node_modules
      - run:
          name: Install functions
          command: npm --prefix functions install
      - save_cache:
          key: dependency-cache-{{ checksum "functions/package-lock.json" }}
          paths:
            - functions/node_modules
  deploy:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install firebase tools
          command: sudo npm install -g firebase-tools
      - run:
          name: Deploy
          command: firebase deploy --token $CIRCLE_FIREBASE

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master